### ISSUE TITLE
写真登録機能

### ISSUE THREAD

**Issue by s-chihiro0108** [soikawachihiro41/osimemo#9]
現在、写真アップロードにCarrierWaveとmini_magickを使用しています。写真をアップロード時にエラーが出ます。

エラーの条件
開発環境では、自身のPC、スマホではエラーがおきませんでした。
しかし、他のユーザーのスマホのみエラーが出ます。

fly.ioにディブロイした方は自身のPC、他のユーザーではエラーがありません。しかし、自身のスマホ、他のユーザーもエラーが出ます。（写真がアップロードできない）

まずは、開発環境の他ユーザースマホで出たエラーを下記に記載します。

```
Errno::ENOENT in AlbumsController#create
No such file or directory @ rb_file_s_rename - (/var/folders/l5/yxg_sj5d2xg5zzllw1m915vr0000gn/T/mini_magick20230907-55762-8tdiw6.jpeg, /Users/soikawachihiko/workspace/runteq/PF/osimemori-zu/tmp/1694095131-942376463037276-0001-5783/IMG_1335.jpeg)
Extracted source (around line #23):
21
22
23
24
25
26
              
  process scale: [400, 400]
  def scale(width, height)
    manipulate! do |img|
      Rails.logger.debug "Image path before resizing: #{img.path}"
      img.resize "#{width}x#{height}!"
      Rails.logger.debug "Image path after resizing: #{img.path}"

Rails.root: /Users/soikawachihiko/workspace/runteq/PF/osimemori-zu

Application Trace | Framework Trace | Full Trace
app/uploaders/cover_image_uploader.rb:23:in `scale' 
app/controllers/albums_controller.rb:8:in `create' 
Request

Parameters:

{"authenticity_token"=>"[FILTERED]",
 "album"=>
  {"idol_id"=>"5",
   "name"=>"か",
   "cover_image"=>
    #<ActionDispatch::Http::UploadedFile:0x000000010f0ff6a8
     @content_type="image/jpeg",
     @headers="Content-Disposition: form-data; name=\"album[cover_image]\"; filename=\"IMG_1335.jpeg\"\r\n" + "Content-Type: image/jpeg\r\n",
     @original_filename="IMG_1335.jpeg",
     @tempfile=#<File:/var/folders/l5/yxg_sj5d2xg5zzllw1m915vr0000gn/T/RackMultipart20230907-55762-27lrja.jpeg>>,
   "is_public"=>"1",
   "is_open"=>"1"},
 "button"=>""}
Toggle session dump
Toggle env dump
Response

Headers:

None

```

上記のコードを解析すると一時ディレクトリがありません。との内容だと思います。mini_magickは一時ディレクトリーファイルは自動で作成してくれると思うのですが、、

また、（process scale: [400, 400]）一旦これをコメントアウトさせるとエラーはなくなります。

この問題を解決したいです。お手数ではございますがお願いいたします。

**Comment by kenchasonakai** [comment]
すいません、状況をイメージするのがなかなか難しいため、エラーが起きたときの操作とエラーを環境別にスクリーンショットや開発環境・本番環境のログなどを使って詳しく説明していただいて良いでしょうか？

> また、（process scale: [400, 400]）一旦これをコメントアウトさせるとエラーはなくなります。

こちらもどういった意図で書いているのか教えていただいて良いでしょうか？
また、どういったコードを書いているのかも記載していただけるとわかりやすくなるかと思います

**Comment by s-chihiro0108** [comment]
すみません。わかりずらくて、、

開発環境でエラーログが出るのが他の方のスマホのみ出ます。
![S__53288988](https://github.com/soikawachihiro41/osimemo/assets/122589198/8c7b2344-53e7-4d2b-9ed0-0e652ce8b260)

>こちらもどういった意図で書いているのか教えていただいて良いでしょうか？
>また、どういったコードを書いているのかも記載していただけるとわかりやすくなるかと思います

こちらの意図としてはエラーの原因はおそらくmini_magickではなのかという意図で記載しています。しかし、mini_magickで画像調整は機能として使用したいのでコメントアウトのままだと困ってしまいます。


質問内容としてはエラーは解消したいがmini_magickも使用したい（画像のリサイズのため）、この実装をしたいという内容です。

下記に関連コードを記載いたします。お手数お掛けいたしますが、よろしくお願いいたします。

```
class PhotosController < ApplicationController
  before_action :login_required
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :check_owner_or_uploader, only: [:edit, :update, :destroy]

  def new
    @photo = Photo.new
    # 自身がオーナーのアルバム
    @my_albums = Album.where(user_id: current_user.id)
    # 公開設定かつ写真追加が許可されているアルバム
    @open_albums = Album.where(is_public: true, is_open: true).where.not(user_id: current_user)
  end
  
  def create
    selected_album_id = params[:my_album_id].present? ? params[:my_album_id] : params[:open_album_id]
    @album = Album.find(selected_album_id)
    
    @photo = @album.photos.new(photo_params)
    tag_list = params[:photo][:tag_names].split(',') 
    @photo.uploader_id = current_user.id
    if @photo.save
      @photo.save_tags(tag_list)
      redirect_to mypages_path, notice: '登録が完了しました'
    else
      flash.now[:danger] = 'エラーが発生しました。入力内容を確認してください。'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @album = Album.find(@photo.album_id)
    @tag_names = @photo.tags.pluck(:tag_names)
  end
  
  def index
    idol = Idol.find(params[:idol_id])
    @album = idol.albums.find(params[:album_id])
    @photos = @album.photos
  end
  
  def edit
    @photo = Photo.find(params[:id])
    # 自身がオーナーのアルバム
    @my_albums = Album.where(user_id: current_user.id)
    # 公開設定かつ写真追加が許可されているアルバム
    @open_albums = Album.where(is_public: true, is_open: true).where.not(user_id: current_user.id)
    @tag_names = @photo.tags.pluck(:tag_names).join(',')
  end
  
  # PhotosController 内の update メソッド
def update
  selected_album_id = params[:my_album_id].present? ? params[:my_album_id] : params[:open_album_id]
  @album = Album.find(selected_album_id)
  
  @photo = Photo.find(params[:id])
  tag_list = params[:photo][:tag_names].presence&.split(',')
  
  if @photo.update(photo_params.except(:tag_names))
    @photo.album = @album
    @photo.save_tags(tag_list || [])
    @photo.save
    redirect_to mypages_url(tab: 'photos'), notice: '写真が正常に更新されました。'
  else
    flash.now[:danger] = 'エラーが発生しました。入力内容を確認してください。'
    render :edit, status: :unprocessable_entity
  end
end


def tag
  # is_publicがtrueに設定されたアルバムのIDを取得
  public_album_ids = Album.where(is_public: true).pluck(:id)

  # タグに紐づいていて、かつ公開されているアルバムに所属している写真のみを取得
  @photos = Photo.joins(:tags, :album).where(tags: { tag_names: params[:tag] }).where(albums: { id: public_album_ids })

  render :index
end


  
  def destroy
    @photo.destroy
    redirect_to mypages_url(tab: 'photos'), notice: '写真が正常に削除されました。'
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def check_owner_or_uploader
    unless current_user.id == @photo.album.user_id || current_user.id == @photo.uploader_id
      redirect_to root_path, alert: '権限がありません。'
    end
  end
    
  private

  def photo_params
    params.require(:photo).permit(:image, :body, :album_id, :capture_date, :tag_names)
  end
end
```
```
class CoverImageUploader < CarrierWave::Uploader::Base

  include CarrierWave::MiniMagick

  # 画像リサイズ（800x800に合わせる）
  #process resize_to_fit: [300, 300]

  # Choose what kind of storage to use for this uploader:
  storage :fog

  # Override the directory where uploaded files will be stored.
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  # Provide a default URL as a default if there hasn't been a file uploaded:
  def default_url(*args)
    "/assets/default-profile-image.jpg"
  end

  process scale: [400, 400]
  def scale(width, height)
    manipulate! do |img|
      Rails.logger.debug "Image path before resizing: #{img.path}"
      img.resize "#{width}x#{height}!"
      Rails.logger.debug "Image path after resizing: #{img.path}"
      img
    rescue => e
      Rails.logger.error "An error occurred: #{e.message}"
      raise e
    end
  end
  
  # 画像の拡張子を制限
  def extension_allowlist
    %w(jpg jpeg gif png)
  end

  # 一意のファイル名を生成
  def filename
    "#{secure_token}.#{file.extension}" if original_filename
  end

  protected

  def secure_token
    var = :"@#{mounted_as}_secure_token"
    model.instance_variable_get(var) || model.instance_variable_set(var, SecureRandom.uuid)
  end
end
```
```
class Photo < ApplicationRecord
  belongs_to :album
  belongs_to :uploader, class_name: 'User', foreign_key: 'uploader_id'
  has_many :photo_tags, dependent: :destroy
  has_many :tags, through: :photo_tags
  mount_uploader :image, CoverImageUploader
  attr_accessor :tag_names

  validates :image, presence: true
  validates :album_id, presence: true
  validates :capture_date, presence: true

  def save_tags(sent_tags)
    current_tags = self.tags.pluck(:tag_names) || []
    sent_tags ||= []

    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    
    old_tags.each do |old|
      tag = Tag.find_by(tag_names: old)
      photo_tag = self.photo_tags.find_by(tag_id: tag.id)
      photo_tag&.destroy
    end
    
    new_tags.each do |new|
      tag = Tag.find_or_create_by(tag_names: new)
      self.photo_tags.create(tag: tag)
    end
  end
end
```
